# Generated by Django 3.2 on 2022-03-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220315_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity_as_float',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
