# Generated by Django 3.2 on 2022-03-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20220315_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='servings',
            new_name='serves',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
