# Generated by Django 3.2 on 2022-03-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_comment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='I forgot to add the ingredients!'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
